# Created articles go here!!!
Article.destroy_all

Article.create(title: 'The Weirdly Enduring Appeal of Weird Al Yankovic', body: 'Last summer, in the middle of what struck me as an otherwise very full life, I went to my first Weird Al Yankovic concert. Weird Al, for anyone reading this through a golden monocle, is the most renowned comedy musician in the history of the multiverse — a force of irrepressible wackiness who, back in the 1980s, built a preposterous career out of song parodies and then, somehow, never went away. After 40 years, Yankovic is now no longer a novelty, but an institution — a garish bright patch in the middle of America’s pop-cultural wallpaper, a completely ridiculous national treasure, an absurd living legend.', published: true)
Article.create(title: 'A Yellow Card, Then Unfathomable Violence, in Brazil', body: 'PIO XII, Brazil — It was midafternoon that Sunday when Otávio Jordão da Silva Cantanhede left on his bike to play pickup soccer. His father said he did not see him tuck a knife into his shorts or slide a blade into his backpack. At 19, short and thin, Cantanhede rode through the remote town in northeastern Brazil with his younger brother George. They headed for the neighborhood of Centro do Meio, a few miles away down a red dirt road. The lumpy soccer field had wooden goal posts with no nets.', published: false)
Article.create(title: 'Solitary in Iran Nearly Broke Me. Then I went Inside Americas Prisons.', body: 'For hours, days, I fixated on the patch of sunlight cast against my wall through those barred and grated windows. When, after five weeks, my knees buckled and I fell to the ground utterly broken, sobbing and rocking to the beat of my heart, it was the patch of sunlight that brought me back.', published: false)
Article.create(title: 'Superman Of Havana', body: 'The mayor’s son drew on his cigarette, thought back sixty years, paused, and made a chopping motion on his lower thigh—fifteen inches, give or take, from his groin to just above his knee. “The women said, ‘He has a machete.’” The mayor’s son is in his seventies now, but he was a teenager back then, during the years of Havana’s original sin. He thought back to his father as a young man, a lotto numbers runner who rose to the mayoralty of the gritty Barrio de Los Sitios, in Centro Habana. His dad loved mingling with the stars that flocked to the capital, and he sometimes took his boy to meet them: Brando, Nat King Cole, and that old borrachón Hemingway. ', published: true)
Article.create(title: 'Beyond the Matrix', body: 'On the monitor screen, Tom Hanks’s eyes, in extreme closeup, flickered through a complicated sequence of emotions: hatred, fear, anger, doubt. “Cut!” Lana Wachowski shouted. The crew on Stage 9 at Babelsberg Studio, near Berlin, erupted in a din of professional efficacy, preparing for the next shot, while Hanks returned to his chair to sip coffee from an NPR cup. Lana and her brother, Andy, who are best known for writing and directing the “Matrix” trilogy, were shooting “Cloud Atlas,” an adaptation of David Mitchell’s 2004 best-selling novel of the same name.', published: false)
Article.create(title: 'The Night New York Avoided a Riot', body: 'In the days following Martin Luther King, Jr.’s assassination, more than 100 cities experienced significant civil disturbance. In New York, everyone expected riots. What happened next. Martin Luther King, Jr. was assassinated in Memphis a little after 6 p.m., Central Standard Time, on April 4, 1968. As the news spread around the country, angry and grieving inner-city residents poured into the streets. In many places, marches and protests broke out; in some, the crowds turned violent. Scores of shops and restaurants along Washington’s 14th Street were looted that night, and several were set on fire, some only a few minutes’ drive from the White House. Over the following few days, more than 100 cities would experience significant civil disturbance. ', published: true)


